name: Action Workflow

on: [push]

jobs:
  run-guthub-action:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Action
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Mona the Octocat'

