name: Server Start Stop

on:
  workflow_dispatch:
    inputs:
      envName:
        description: Environment Name
        type: choice
        options:
          - "devl"
          - "qual"
          - "cert"
        required: true

      serverName:
        required: true
        type: string
        description: Enter the end server name(s) separated with commas

      command:
        description: 	Command
        type: choice
        options:
          - "start"
          - "stop"
          - "restart"
        required: true

jobs:
  app-server-start-stop:
    runs-on: ubuntu-latest

    steps:
      - name: Logging inputs
        env:
          environmentName: ${{ github.event.inputs.environmentName }}
          serverName: ${{ github.event.inputs.serverName }}
          command: ${{ github.event.inputs.command }} 
          
        run: |
          echo "environmentName=${environmentName}"
          echo "serverName=${serverName}"
          echo "command=${command}"
          
          IFS=',' read -ra ServerNameArray <<< "${{ github.event.inputs.serverName }}";
          for Servername in "${ServerNameArray[@]}"; do
            echo "ServerName:${Servername}"
          done
          
